# Generated by Django 5.2.8 on 2026-03-06 20:01

import django.db.models.deletion
import tutorials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER')], max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=40)),
                ('display_name', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutorial_profile',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('material_type', models.CharField(choices=[('note', 'NOTE'), ('worksheet', 'WORKSHEET'), ('question_paper', 'QUESTION_PAPER')], max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to=tutorials.models.material_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepts_submissions', models.BooleanField(default=True, help_text='If True, students can upload answers (e.g. for worksheets/question papers).')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to='tutorials.profile')),
            ],
            options={
                'db_table': 'tutorial_material',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_file', models.FileField(upload_to=tutorials.models.submission_upload_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tutorials.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tutorials.profile')),
            ],
            options={
                'db_table': 'tutorial_student_submission',
                'ordering': ['-submitted_at'],
                'unique_together': {('material', 'student')},
            },
        ),
    ]
